name: MVC

folders:
  - lib/controllers
  - lib/models
  - lib/views

  - lib/services
  - lib/routes

  - lib/core
  - lib/core/constants
  - lib/core/theme
  - lib/core/utils

  - lib/shared
  - lib/shared/widgets

dependencies: []

dev_dependencies: []

files:
  - from: files/main.dart
    to: lib/main.dart

  - from: files/app.dart
    to: lib/app.dart
