name: arise
description: A modular CLI for bootstrapping production-ready Flutter projects with architecture, state management, routing, and networking.
version: 1.0.0
repository: https://github.com/khanadnan10/arise
homepage: https://github.com/khanadnan10/arise
issue_tracker: https://github.com/khanadnan10/arise/issues

topics:
  - flutter
  - cli
  - code-generation
  - scaffolding
  - dart
environment:
  sdk: ^3.9.2

executables:
  arise: arise

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.26.0
