name: GetX
category: state_management
description: High-performance state management, navigation, and dependency injection.
version: 1.0.0
author: Arise

folders: []

packages:
  - name: get

files: []

requires: []
conflicts:
  - riverpod
  - provider
  - bloc
