name: Provider
category: state_management
description: Simple and flexible state management using InheritedWidget.
version: 1.0.0
author: Arise

folders: []

packages:
  - name: provider

files: []

requires: []
conflicts:
  - riverpod
  - bloc
  - getx
