name: Riverpod
category: state_management
description: Compile-safe reactive state management by Remi Rousselet.
version: 1.0.0
author: Arise

folders: []

packages:
  - name: flutter_riverpod

requires: []
conflicts:
  - provider
  - bloc
  - getx
